### ISSUE TITLE
nodejs express example

### ISSUE THREAD

**Issue by LorisLombardo87** [vflorusso/botrevolution#2]
Ciao,
potreste caricare o linkare un esempio del bot framework con express anzichè con restify?
grazie, Loris...

**Comment by vflorusso** [comment]
CIao, questo esempio è fatto con express: https://github.com/Microsoft/BotBuilder-Samples/tree/86ebba09bfe5ccfdbbd66eaf9c7d19fa9bb239d1/Node/demo-ContosoFlowers

Facci sapere se è sufficiente :)
